services:
  - type: web
    name: meetingmind-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WHISPER_MODEL
        value: "tiny"
      - key: RENDER
        value: "True"
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
