"""Add soft deletes and indexing

Revision ID: e93601793503
Revises: 547aab4c142c
Create Date: 2026-06-01 18:44:53.482637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93601793503'
down_revision: Union[str, Sequence[str], None] = '547aab4c142c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_action_items_is_deleted'), 'action_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_index(op.f('ix_chat_history_meeting_id'), 'chat_history', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_name'), 'meeting_participants', ['name'], unique=False)
    op.add_column('meetings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_meetings_created_at'), 'meetings', ['created_at'], unique=False)
    op.create_index(op.f('ix_meetings_date'), 'meetings', ['date'], unique=False)
    op.create_index(op.f('ix_meetings_is_deleted'), 'meetings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_is_deleted'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_at'), table_name='meetings')
    op.drop_column('meetings', 'is_deleted')
    op.drop_index(op.f('ix_meeting_participants_name'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_chat_history_meeting_id'), table_name='chat_history')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_is_deleted'), table_name='action_items')
    op.drop_column('action_items', 'is_deleted')
    # ### end Alembic commands ###
